server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
security:
  basic:
    enabled: true
  user:
    name: admin
    password: tcltest