server:
  port: 8881
spring:
  application:
    name: appcenter-api
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  data:
      mongodb:
        uri: mongodb://10.128.208.160:27017/appcenter?AutoConnectRetry=true
        database: appcenter
eureka:
  client:
    service-url:
      defaultZone: http://admin:tcltest@localhost:8761/eureka/
