server:
  port: 8882
spring:
  application:
    name: appcenter-zuul
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://admin:tcltest@localhost:8761/eureka/
#自定义指定微服务的访问路径
zuul:
  prefix: /appcenter #指定路由前缀
  ignored-services: '*' #默认忽略所有微服务，只代理下面显示声明的微服务
  routes:
    appcenter-api: /api/**
    appcenter-cms: /cms/**
#  host:
#    socket-timeout-millis: 10000
#    connect-timeout-millis: 10000

#解决hystrix+feign超时设置
feign:
  hystrix: #开启feign支持hystrix (注意:一定要开启，旧版本默认支持，新版本默认关闭)
    enabled: true

ribbon:
  ReadTimeout: 2000 #超时时间
  ConnectTimeout: 2000 #连接时间
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试

#hystrix:
#  command:
#    appcenter-api:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 8000







